-- V41 — Contact & Communication + consistent featured resources
-- Run AFTER SUPABASE_PATCH_V40.sql. Safe to run once; existing rows are preserved.

alter table public.resources add column if not exists featured boolean not null default false;
create index if not exists resources_featured_idx on public.resources(featured) where featured=true;

-- Contact enquiries submitted by the public website.
create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254),
  category text not null default 'General enquiry' check (char_length(category) between 1 and 80),
  subject text not null default '' check (char_length(subject) <= 180),
  message text not null check (char_length(message) between 10 and 5000),
  status text not null default 'new' check (status in ('new','read','replied','archived')),
  source text not null default 'portfolio-website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contact_inquiries enable row level security;

-- Public visitors may submit enquiries, but cannot read/update/delete them.
drop policy if exists "Public can submit contact enquiries" on public.contact_inquiries;
create policy "Public can submit contact enquiries"
  on public.contact_inquiries for insert to anon, authenticated
  with check (true);

-- Admins may manage the inbox.
drop policy if exists "Admins can read contact enquiries" on public.contact_inquiries;
create policy "Admins can read contact enquiries"
  on public.contact_inquiries for select to authenticated
  using (public.is_admin());

drop policy if exists "Admins can update contact enquiries" on public.contact_inquiries;
create policy "Admins can update contact enquiries"
  on public.contact_inquiries for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can delete contact enquiries" on public.contact_inquiries;
create policy "Admins can delete contact enquiries"
  on public.contact_inquiries for delete to authenticated
  using (public.is_admin());

create index if not exists contact_inquiries_created_idx on public.contact_inquiries(created_at desc);
create index if not exists contact_inquiries_status_idx on public.contact_inquiries(status);

-- Timestamp trigger, using the same convention as the rest of the portfolio.
create or replace function public.set_contact_inquiry_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists contact_inquiries_updated_at on public.contact_inquiries;
create trigger contact_inquiries_updated_at before update on public.contact_inquiries
for each row execute function public.set_contact_inquiry_updated_at();
