-- V39 — CMS / Media Library
-- Run this once in Supabase SQL Editor after the existing portfolio schema/patches.
create table if not exists public.media_library (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text not null default '',
  category text not null default '',
  file_name text not null default '',
  storage_path text not null default '',
  public_url text not null default '',
  mime_type text not null default '',
  file_size bigint not null default 0,
  thumbnail_path text not null default '',
  thumbnail_url text not null default '',
  published boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.media_library enable row level security;
drop policy if exists "Public can read published media" on public.media_library;
drop policy if exists "Admins can manage media library" on public.media_library;
create policy "Public can read published media" on public.media_library for select using (published = true);
create policy "Admins can manage media library" on public.media_library for all to authenticated using (public.is_admin()) with check (public.is_admin());
create index if not exists media_library_sort_idx on public.media_library(sort_order,id);
create index if not exists media_library_published_idx on public.media_library(published);
create index if not exists media_library_featured_idx on public.media_library(featured);
-- Ensure the existing public storage bucket can be used by the dashboard.
-- If your portfolio-media bucket does not exist, create a PUBLIC bucket named portfolio-media in Storage.
